import simd

enum VoxelType: UInt8, Codable {
    case air = 0
    case grass
    case dirt
    case stone
    case sand
    case snow
    case water
    case wood
    case leaves
    // Crafted-only — never generated by TerrainGenerator, only produced via
    // CraftingRecipes. Otherwise behave exactly like any other block
    // (placeable, breakable, droppable): nothing else needed to add them.
    case planks
    case stoneBricks
    case mudBricks
    case packedSnow
    case thatch
    case polishedStone
    case sandstone
    case reinforcedPlanks
    case packedDirt
    // A tool, not a block: crafted and carried like any other item, but not
    // solid (so it can't be placed as terrain — see Renderer.placeBlock) and
    // never targeted by breaking. Using it opens MapView instead (the M key,
    // gated on holding at least one — see AppDelegate.toggleMap).
    case map
    // Dropped by animals on death (see Renderer.spawnAnimalDrops) — items,
    // not blocks: same non-solid/non-placeable treatment as .map.
    case bone
    case rawPork
    case rawMutton
    case rawChicken
    // Crafted-only, same as planks/stoneBricks above — a real solid/placeable
    // block (not a tool/item like map or the meats), gates a second crafting
    // tier by proximity (see CraftingRecipe.requiresCraftingTable and
    // Renderer.isNearCraftingTable). Appended at the end, not sorted in with
    // the other crafted blocks above, so every existing case keeps its raw
    // UInt8 value — this enum's raw value is what block edits are saved as
    // (see BlockEdits/WorldStore), and reordering would corrupt old saves.
    case craftingTable

    private static let nonSolidTypes: Set<VoxelType> = [.air, .map, .bone, .rawPork, .rawMutton, .rawChicken]
    var isSolid: Bool { !Self.nonSolidTypes.contains(self) }

    var color: SIMD3<Float> {
        switch self {
        case .air:               return .zero
        case .grass:             return SIMD3<Float>(0.30, 0.55, 0.22)
        case .dirt:              return SIMD3<Float>(0.40, 0.28, 0.18)
        case .stone:             return SIMD3<Float>(0.45, 0.42, 0.40)
        case .sand:              return SIMD3<Float>(0.76, 0.70, 0.50)
        case .snow:              return SIMD3<Float>(0.95, 0.95, 0.97)
        case .water:             return SIMD3<Float>(0.15, 0.40, 0.75)
        case .wood:              return SIMD3<Float>(0.36, 0.25, 0.15)
        case .leaves:            return SIMD3<Float>(0.16, 0.42, 0.14)
        case .planks:            return SIMD3<Float>(0.62, 0.46, 0.28)
        case .stoneBricks:       return SIMD3<Float>(0.55, 0.53, 0.52)
        case .mudBricks:         return SIMD3<Float>(0.55, 0.38, 0.24)
        case .packedSnow:        return SIMD3<Float>(0.88, 0.90, 0.95)
        case .thatch:            return SIMD3<Float>(0.62, 0.55, 0.20)
        case .polishedStone:     return SIMD3<Float>(0.58, 0.56, 0.55)
        case .sandstone:         return SIMD3<Float>(0.80, 0.72, 0.52)
        case .reinforcedPlanks:  return SIMD3<Float>(0.50, 0.40, 0.30)
        case .packedDirt:        return SIMD3<Float>(0.35, 0.24, 0.15)
        case .map:               return SIMD3<Float>(0.82, 0.74, 0.52)
        case .bone:              return SIMD3<Float>(0.90, 0.87, 0.76)
        case .rawPork:           return SIMD3<Float>(0.88, 0.58, 0.58)
        case .rawMutton:         return SIMD3<Float>(0.78, 0.38, 0.40)
        case .rawChicken:        return SIMD3<Float>(0.92, 0.72, 0.68)
        case .craftingTable:     return SIMD3<Float>(0.44, 0.30, 0.16)
        }
    }

    /// Seconds to break in survival mode. Only meaningful for solid types —
    /// air/water aren't breakable at all (see Renderer.raycastTargetBlock,
    /// which only ever targets isSolid blocks).
    var breakDuration: Float {
        switch self {
        case .stone, .stoneBricks, .polishedStone: return 1.2
        case .wood, .planks, .reinforcedPlanks, .craftingTable: return 0.8
        case .leaves, .thatch: return 0.25
        case .grass, .dirt, .sand, .snow, .mudBricks, .packedSnow, .sandstone, .packedDirt: return 0.4
        case .air, .water, .map, .bone, .rawPork, .rawMutton, .rawChicken: return 0.4
        }
    }

    /// Human-readable name — hotbar/inventory/crafting labels.
    var displayName: String {
        switch self {
        case .air:               return "Air"
        case .grass:             return "Grass"
        case .dirt:              return "Dirt"
        case .stone:             return "Stone"
        case .sand:              return "Sand"
        case .snow:              return "Snow"
        case .water:             return "Water"
        case .wood:              return "Wood"
        case .leaves:            return "Leaves"
        case .planks:            return "Planks"
        case .stoneBricks:       return "Stone Bricks"
        case .mudBricks:         return "Mud Bricks"
        case .packedSnow:        return "Packed Snow"
        case .thatch:            return "Thatch"
        case .polishedStone:     return "Polished Stone"
        case .sandstone:         return "Sandstone"
        case .reinforcedPlanks:  return "Reinforced Planks"
        case .packedDirt:        return "Packed Dirt"
        case .map:               return "Map"
        case .bone:              return "Bone"
        case .rawPork:           return "Raw Pork"
        case .rawMutton:         return "Raw Mutton"
        case .rawChicken:        return "Raw Chicken"
        case .craftingTable:     return "Crafting Table"
        }
    }
}
